version: '3.8'

services:
    vetsapapp_db:
        image: postgres:17
        platform: linux/amd64
        container_name: vetsapapp_db
        environment:
            POSTGRES_DB: vetsapapp
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - '7432:5432'
    vetsapapp_redis:
        image: redis:6
        container_name: vetsapapp_redis
        ports:
            - '7379:6379'
